spring:
  datasource:
#   数据源基本配置
    username: root
    password: 311
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.108.71.48:3306/video
    type: com.alibaba.druid.pool.DruidDataSource
#   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
#   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,logback
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

  # 上传文件大小限制
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  redis:
    host: 39.108.71.48
    #
mybatis:
  # 指定sql映射文件位置
  mapper-locations: classpath:mapper/*.xml
server:
  tomcat:
    uri-encoding: utf-8
thymeleaf:
           cache: false
shiro:
  loginUrl: /login
  successUrl: /hello
  unauthorizedUrl: /error

# mybatis分页插件的使用
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


logging:
  level:
     com.hniu.mapper: debug
